# Generated by Django 4.1.3 on 2023-02-26 13:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.BooleanField()),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(25)])),
                ('owner_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_stavka', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
