# Generated by Django 4.1.3 on 2023-02-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stavka',
            name='color',
            field=models.CharField(max_length=1),
        ),
    ]
